sudo: required
service: 
    - docker

before_install:
    - docker build -t mskjoldebrand/react-test -f ./client/Dockerfile.dev ./client

script:
    - docker run -e CI=true USERNAME/react-test npm test

after_success:
    - docker build -t mskjoldebrand/multi-client ./client
    - docker build -t mskjoldebrand/multi-nginx ./nginx
    - docker build -t mskjoldebrand/multi-worker ./worker
    - docker build -t mskjoldebrand/multi-server ./server

    # Log in to Docker hub

    - echo "$DOCKER_PW" | docker login -u "$DOCKER_ID" --password-stdin
    
    # Push the built images to Docker Hub
    - docker push mskjoldebrand/multi-client
    - docker push mskjoldebrand/multi-nginx
    - docker push mskjoldebrand/multi-worker
    - docker push mskjoldebrand/multi-server



